server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
  security:
    user:
      name: raghava
      password: raghava
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/raghava219/spring-cloudconfig-wa-tolls
          search-paths:
            - station*
          repos:
            perf:
              pattern: "*/perf"
              uri: https://github.com/raghava219/spring-cloudconfig-wa-tolls-perf/
              search-paths:
                - "station*"
